# Generated by Django 5.2.11 on 2026-03-04 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppStoreSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_transaction_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('transaction_id', models.CharField(max_length=255)),
                ('product_id', models.CharField(db_index=True, max_length=255)),
                ('bundle_id', models.CharField(max_length=255)),
                ('environment', models.CharField(max_length=20)),
                ('expires_date', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('last_notification_type', models.CharField(blank=True, max_length=100)),
                ('last_notification_subtype', models.CharField(blank=True, max_length=100)),
                ('original_purchase_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'App Store Subscription',
                'ordering': ['-updated_at'],
            },
        ),
    ]
